---
title: 'Short Assignment 1: Quantitative Description of Immigration Data'
author: '[Insert your SID Here]'
date: "October 31, 2025"
output:
  pdf_document: default
  html_document:
    df_print: paged
---


```{r}
# Upload the necessary packages 
library(tidyverse)
```

```{r}
# Upload the dataset 
sea <- read.csv("sea.csv")
```

# Section 1 (10 points)

## a.  

#### Code:

```{r}

```

```{r}

```

```{r}

```

> **Answer:**

```{r}

```

## b. 

#### Code:

```{r}

```

> **Answer:**

```{r}

```


## c.  

#### Code:

```{r}

```

> **Answer:**

```{r}

```

## d.

#### Code:

```{r}

```

```{r}

```

> **Answer:**

```{r}

```

## e.  

> **Answer:**

```{r}

```

## f.  

> **Answer:**

```{r}

```

## g.  

> **Answer:**

```{r}

```

## h. 

#### Code:

```{r}

```

> **Answer:**

```{r}

```


## i.  

> **Answer:**

```{r}

```

# EXTRA CREDIT (2 points)

## j

#### Code:

```{r}

```

> **Answer:**

```{r}

```

## k.

#### Code:

```{r}

```

> **Answer:**

```{r}

```

## l. 

#### Code:

```{r}

```

> **Answer:**

```{r}

```




